---
server:
 port: 8888
spring:
 cloud: 
  config:
   server:
    git:
     uri: https://github.com/shomveerKherwa/spring-cloudconfig-wa-tolls
     search-paths: 
      - 'station*' 
     repos:
       perf:
        pattern:
         - "*/perf"
        uri: https://github.com/shomveerKherwa/spring-cloudconfig-wa-tolls-performance
        search-paths: 
           - 'station*'
 security:
  basic:
    enabled: true
  user:
    name: pluralsight
    password: pluralsight
       
    